env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    DEBIAN_FRONTEND: "noninteractive"
    CHERISH_WORKING_DIR: "/home/kernelpanix/LunarisAOSP"
    CIRRUS_OUT_DIR: "/home/kernelpanix/out/LunarisAOSP"
    PD_API_KEY: ENCRYPTED[34bc583e19c47c56dc0c1f9950553e9d9c8ec6dcee3c46ed85b83d089ae3e7546324f893ff919531195207645caf9333]
    SF_PASSWORD: ENCRYPTED[134c9f2823c604c8aae1c1f5ec7b34d7773665677a0d36c41883026c6b703f5362b2d92eebeb550c9a2707fbe337d721]

task:
  name: Enviroment
  skip: $CIRRUS_BRANCH != 'LunarisAOSP-A16'
  alias: Enviroment
  persistent_worker:
  timeout_in: 24h

  script:
    - echo "Starting setup environment..."
    - echo $(pwd)

  check_script:
    - echo $(nproc --all)
    - echo $(free -mh)
    - echo $(df -h)

  enviroment_script:
    - rm -rf $CIRRUS_OUT_DIR
    - mkdir -p $CIRRUS_OUT_DIR
    - rm -rf $CIRRUS_WORKING_DIR/out/.lock
    - cd $CIRRUS_OUT_DIR
    - wget https://github.com/ling-zhou/rust-sshpass/releases/download/1.1.5/sshpass-1.1.5-x86_64-linux.tar.xz
    - tar -xvf sshpass-1.1.5-x86_64-linux.tar.xz
    - wget https://github.com/ManuelReschke/go-pd/releases/download/v1.5.0/go-pd_1.5.0_linux_amd64.tar.gz
    - tar -xvf go-pd_1.5.0_linux_amd64.tar.gz

task:
  name: Xiaomi 12
  skip: $CIRRUS_BRANCH != 'LunarisAOSP-A16'
  alias: CupidBuild
  depends_on: Enviroment
  persistent_worker:
  timeout_in: 24h
  cupid_script:
    - cd $CHERISH_WORKING_DIR
    - cd packages/apps/Settings
    - git add -vAf
    - git reset --hard HEAD
    - sed -i 's/Nothing Phone 2/Xiaomi 12/g' res/values/lunaris_strings.xml
    - sed -i 's/8+ G/8 G/g' res/values/lunaris_strings.xml
    - sed -i 's/4700 mAh/4500 mAh/g' res/values/lunaris_strings.xml
    - sed -i 's/Amoled 120hz/Amoled 120hz/g' res/values/lunaris_strings.xml
    - DEVICE="cupid"
    - cd $CHERISH_WORKING_DIR
    - . build/envsetup.sh > /dev/null 2>&1 || true
    - lunch lineage_$DEVICE-bp2a-user && m lunaris -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/Lunaris*-$DEVICE-*.zip $CIRRUS_OUT_DIR/

task:
  name: Xiaomi 12 Pro
  skip: $CIRRUS_BRANCH != 'Lunaris-A16'
  persistent_worker:
  timeout_in: 24h
  alias: ZeusBuild
  depends_on: CupidBuild
  zeus_script:
    - cd $CHERISH_WORKING_DIR
    - cd packages/apps/Settings
    - git add -vAf
    - git reset --hard HEAD
    - sed -i 's/Nothing Phone 2/Xiaomi 12 Pro/g' res/values/lunaris_strings.xml
    - sed -i 's/8+ G/8 G/g' res/values/lunaris_strings.xml
    - sed -i 's/4700 mAh/4600 mAh/g' res/values/lunaris_strings.xml
    - sed -i 's/Amoled 120hz/Amoled 120hz/g' res/values/lunaris_strings.xml
    - DEVICE="zeus"
    - cd $CHERISH_WORKING_DIR
    - . build/envsetup.sh > /dev/null 2>&1 || true
    - lunch lineage_$DEVICE-bp2a-user && m lunaris -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/Lunaris*-$DEVICE-*.zip $CIRRUS_OUT_DIR/

task:
  name: Xiaomi 12S
  skip: $CIRRUS_BRANCH != 'Lunaris-A16'
  persistent_worker:
  timeout_in: 24h
  alias: MayflyBuild
  depends_on: ZeusBuild
  mayfly_script:
    - cd $CHERISH_WORKING_DIR
    - cd packages/apps/Settings
    - git add -vAf
    - git reset --hard HEAD
    - sed -i 's/Nothing Phone 2/Xiaomi 12/g' res/values/lunaris_strings.xml
    - sed -i 's/4700 mAh/4500 mAh/g' res/values/lunaris_strings.xml
    - sed -i 's/Amoled 120hz/Amoled 120hz/g' res/values/lunaris_strings.xml
    - DEVICE="mayfly"
    - cd $CHERISH_WORKING_DIR
    - . build/envsetup.sh > /dev/null 2>&1 || true
    - lunch lineage_$DEVICE-bp2a-user && m lunaris -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/Lunaris*-$DEVICE-*.zip $CIRRUS_OUT_DIR/

task:
  name: Xiaomi 12S Pro
  skip: $CIRRUS_BRANCH != 'Lunaris-A16'
  persistent_worker:
  timeout_in: 24h
  alias: UnicornBuild
  depends_on: MayflyBuild
  unicorn_script:
    - cd $CHERISH_WORKING_DIR
    - cd packages/apps/Settings
    - git add -vAf
    - git reset --hard HEAD
    - sed -i 's/Nothing Phone 2/Xiaomi 12S Pro/g' res/values/lunaris_strings.xml
    - sed -i 's/4700 mAh/4500 mAh/g' res/values/lunaris_strings.xml
    - sed -i 's/Amoled 120hz/Amoled 120hz/g' res/values/lunaris_strings.xml
    - DEVICE="unicorn"
    - cd $CHERISH_WORKING_DIR
    - . build/envsetup.sh > /dev/null 2>&1 || true
    - lunch lineage_$DEVICE-bp2a-user && m lunaris -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/Lunaris*-$DEVICE-*.zip $CIRRUS_OUT_DIR/

task:
  name: Xiaomi 12T Pro
  skip: $CIRRUS_BRANCH != 'Lunaris-A16'
  persistent_worker:
  timeout_in: 24h
  alias: DitingBuild
  depends_on: UnicornBuild
  diting_script:
    - cd $CHERISH_WORKING_DIR
    - cd packages/apps/Settings
    - git add -vAf
    - git reset --hard HEAD
    - sed -i 's/Nothing Phone 2/Xiaomi 12T Pro/g' res/values/lunaris_strings.xml
    - sed -i 's/4700 mAh/5000 mAh/g' res/values/lunaris_strings.xml
    - sed -i 's/Amoled 120hz/Amoled 120hz/g' res/values/lunaris_strings.xml
    - DEVICE="diting"
    - cd $CHERISH_WORKING_DIR
    - . build/envsetup.sh > /dev/null 2>&1 || true
    - lunch lineage_$DEVICE-bp2a-user && m lunaris -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/Lunaris*-$DEVICE-*.zip $CIRRUS_OUT_DIR/

task:
  name: Upload
  skip: $CIRRUS_BRANCH != 'Lunaris-A16'
  persistent_worker:
  timeout_in: 24h
  depends_on:
    - CupidBuild
    - ZeusBuild
    - MayflyBuild
    - UnicornBuild
    - DitingBuild

  pixeldrain_script:
    - cd $CIRRUS_OUT_DIR/
    -  ./go-pd upload -k $PD_API_KEY *.zip -v
    
  sourceforge_script:
    - cd $CIRRUS_OUT_DIR/
    - ./sshpass -p $SF_PASSWORD rsync -avP ./*.zip dopaemon@frs.sourceforge.net:/home/frs/project/android-unofficial/Android-16/Lunaris
