env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    DEBIAN_FRONTEND: "noninteractive"
    PD_API_KEY: ENCRYPTED[34bc583e19c47c56dc0c1f9950553e9d9c8ec6dcee3c46ed85b83d089ae3e7546324f893ff919531195207645caf9333]
    SF_PASSWORD: ENCRYPTED[134c9f2823c604c8aae1c1f5ec7b34d7773665677a0d36c41883026c6b703f5362b2d92eebeb550c9a2707fbe337d721]
    
task:
  name: Build CherishOS
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'CherishOS-A16'
  skip: $CIRRUS_BRANCH != 'CherishOS-A16'
  persistent_worker:
  timeout_in: 24h

  check_script:
    - echo $(nproc --all)
    - echo $(free -mh)
    - echo $(df -h)

  setup_script:
    - mkdir -p /home/kernelpanix/out/CherishOS
    - rm -rf /home/kernelpanix/CherishOS/out/.lock
    - cd /home/kernelpanix/out/CherishOS
    - wget https://github.com/ling-zhou/rust-sshpass/releases/download/1.1.5/sshpass-1.1.5-x86_64-linux.tar.xz
    - tar -xvf sshpass-1.1.5-x86_64-linux.tar.xz
    - wget https://github.com/ManuelReschke/go-pd/releases/download/v1.5.0/go-pd_1.5.0_linux_amd64.tar.gz
    - tar -xvf go-pd_1.5.0_linux_amd64.tar.gz
  
  cupid_script:
    - DEVICE="cupid"
    - cd /home/kernelpanix/CherishOS
    - . build/envsetup.sh
    - brunch $DEVICE | tee log.txt
    - mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

  zeus_script:
    - DEVICE="zeus"
    - cd /home/kernelpanix/CherishOS
    - . build/envsetup.sh
    - brunch $DEVICE | tee log.txt
    - mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

  mayfly_script:
    - DEVICE="mayfly"
    - cd /home/kernelpanix/CherishOS
    - . build/envsetup.sh
    - brunch $DEVICE | tee log.txt
    - mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

  unicorn_script:
    - DEVICE="unicorn"
    - cd /home/kernelpanix/CherishOS
    - . build/envsetup.sh
    - brunch $DEVICE | tee log.txt
    - mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

  diting_script:
    - DEVICE="diting"
    - cd /home/kernelpanix/CherishOS
    - . build/envsetup.sh
    - brunch $DEVICE | tee log.txt
    - mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

  sourceforge_script:
    - cd /home/kernelpanix/CherishOS
    - ./sshpass -p $SF_PASSWORD rsync -avP ./*.zip dopaemon@frs.sourceforge.net:/home/frs/project/android-unofficial/Android-16/CherishOS

  pixeldrain_script:
    - cd /home/kernelpanix/CherishOS
    -  ./go-pd upload -k $PD_API_KEY *.zip -v
