env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    DEBIAN_FRONTEND: "noninteractive"
    PD_API_KEY: ENCRYPTED[34bc583e19c47c56dc0c1f9950553e9d9c8ec6dcee3c46ed85b83d089ae3e7546324f893ff919531195207645caf9333]
    SF_PASSWORD: ENCRYPTED[134c9f2823c604c8aae1c1f5ec7b34d7773665677a0d36c41883026c6b703f5362b2d92eebeb550c9a2707fbe337d721]

task:
  name: Setup
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h

  check_script:
    - echo $(nproc --all)
    - echo $(free -mh)
    - echo $(df -h)

  setup_script:
    - rm -rf /home/kernelpanix/out/RisingOS
    - mkdir -p /home/kernelpanix/out/RisingOS
    - rm -rf /home/kernelpanix/RisingOS/out/.lock
    - cd /home/kernelpanix/out/RisingOS
    - wget https://github.com/ling-zhou/rust-sshpass/releases/download/1.1.5/sshpass-1.1.5-x86_64-linux.tar.xz
    - tar -xvf sshpass-1.1.5-x86_64-linux.tar.xz
    - wget https://github.com/ManuelReschke/go-pd/releases/download/v1.5.0/go-pd_1.5.0_linux_amd64.tar.gz
    - tar -xvf go-pd_1.5.0_linux_amd64.tar.gz

task:
  name: Xiaomi 12
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h
  cupid_script:
    - DEVICE="cupid"
    - cd /home/kernelpanix/RisingOS
    - . build/envsetup.sh || true
    - riseup $DEVICE user
    - rise b -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/RisingOS-*-$DEVICE-*.zip /home/kernelpanix/out/RisingOS/

task:
  name: Xiaomi 12 Pro
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h
  zeus_script:
    - DEVICE="zeus"
    - cd /home/kernelpanix/RisingOS
    - . build/envsetup.sh || true
    - riseup $DEVICE user
    - rise b -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/RisingOS-*-$DEVICE-*.zip /home/kernelpanix/out/RisingOS/

task:
  name: Xiaomi 12S
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h
  mayfly_script:
    - DEVICE="mayfly"
    - cd /home/kernelpanix/RisingOS
    - . build/envsetup.sh || true
    - riseup $DEVICE user
    - rise b -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/RisingOS-*-$DEVICE-*.zip /home/kernelpanix/out/RisingOS/

task:
  name: Xiaomi 12S Pro
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h
  unicorn_script:
    - DEVICE="unicorn"
    - cd /home/kernelpanix/RisingOS
    - . build/envsetup.sh || true
    - riseup $DEVICE user
    - rise b -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/RisingOS-*-$DEVICE-*.zip /home/kernelpanix/out/RisingOS/

task:
  name: Xiaomi 12T Pro
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h
  diting_script:
    - DEVICE="diting"
    - cd /home/kernelpanix/RisingOS
    - . build/envsetup.sh || true
    - riseup $DEVICE user
    - rise b -j$(nproc --all) | tee log.txt
    - mv out/target/product/$DEVICE/RisingOS-*-$DEVICE-*.zip /home/kernelpanix/out/RisingOS/

task:
  name: Upload
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'RisingOS-A16'
  skip: $CIRRUS_BRANCH != 'RisingOS-A16'
  persistent_worker:
  timeout_in: 24h

  sourceforge_script:
    - cd /home/kernelpanix/out/RisingOS
    - ./sshpass -p $SF_PASSWORD rsync -avP ./*.zip dopaemon@frs.sourceforge.net:/home/frs/project/android-unofficial/Android-16/RisingOS

  pixeldrain_script:
    - cd /home/kernelpanix/out/RisingOS
    -  ./go-pd upload -k $PD_API_KEY *.zip -v
