name: CherishOS - Android 16

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create OUTPUT Folder
        run: |
          mkdir -p /home/kernelpanix/out/CherishOS

      - name: Xiaomi 12
        run: |
          DEVICE="cupid"
          cd /home/kernelpanix/CherishOS
          . build/envsetup.sh
          brunch $DEVICE | tee log.txt
          mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

      - name: SourceForge Upload
         uses: Dylan700/sftp-upload-action@latest
         with:
           server: frs.sourceforge.net
           username: dopaemon
           password: $SF_PASSWORD
           port: 22
           uploads: |
             /home/kernelpanix/out/CherishOS/CherishOS-*-$DEVICE-*.zip => /home/frs/project/android-unofficial/Android-16/CherishOS
         env:
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          DEVICE: "cupid"

      - name: Xiaomi 12 Pro
          DEVICE="zeus"
          cd /home/kernelpanix/CherishOS
          . build/envsetup.sh
          brunch $DEVICE | tee log.txt
          mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

      - name: SourceForge Upload
         uses: Dylan700/sftp-upload-action@latest
         with:
           server: frs.sourceforge.net
           username: dopaemon
           password: $SF_PASSWORD
           port: 22
           uploads: |
             /home/kernelpanix/out/CherishOS/CherishOS-*-$DEVICE-*.zip => /home/frs/project/android-unofficial/Android-16/CherishOS
         env:
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          DEVICE: "zeus"

      - name: Xiaomi 12S
          DEVICE="mayfly"
          cd /home/kernelpanix/CherishOS
          . build/envsetup.sh
          brunch $DEVICE | tee log.txt
          mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

      - name: SourceForge Upload
         uses: Dylan700/sftp-upload-action@latest
         with:
           server: frs.sourceforge.net
           username: dopaemon
           password: $SF_PASSWORD
           port: 22
           uploads: |
             /home/kernelpanix/out/CherishOS/CherishOS-*-$DEVICE-*.zip => /home/frs/project/android-unofficial/Android-16/CherishOS
         env:
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          DEVICE: "mayfly"

      - name: Xiaomi 12S Pro
          DEVICE="unicorn"
          cd /home/kernelpanix/CherishOS
          . build/envsetup.sh
          brunch $DEVICE | tee log.txt
          mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

      - name: SourceForge Upload
         uses: Dylan700/sftp-upload-action@latest
         with:
           server: frs.sourceforge.net
           username: dopaemon
           password: $SF_PASSWORD
           port: 22
           uploads: |
             /home/kernelpanix/out/CherishOS/CherishOS-*-$DEVICE-*.zip => /home/frs/project/android-unofficial/Android-16/CherishOS
         env:
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          DEVICE: "unicorn"

      - name: Xiaomi 12T Pro
          DEVICE="diting"
          cd /home/kernelpanix/CherishOS
          . build/envsetup.sh
          brunch $DEVICE | tee log.txt
          mv out/target/product/$DEVICE/CherishOS-*-$DEVICE-*.zip /home/kernelpanix/out/CherishOS/

       - name: SourceForge Upload
         uses: Dylan700/sftp-upload-action@latest
         with:
           server: frs.sourceforge.net
           username: dopaemon
           password: $SF_PASSWORD
           port: 22
           uploads: |
             /home/kernelpanix/out/CherishOS/CherishOS-*-$DEVICE-*.zip => /home/frs/project/android-unofficial/Android-16/CherishOS
         env:
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          DEVICE: "diting"
